### PR TITLE
Added local module for report generation

### PR DESCRIPTION
**Pull request by WackerO**
Working on a module for creating html reports from Rmd templates (similar to airrflow). Maybe make the report module an nf-core module for re-using in other pipelines?

**Edit, @pinin4fjords**: I was also working on this, so I unified efforts (thanks @WackerO for giving me write). Changes:

- Switched to use https://nf-co.re/modules/rmarkdownnotebook
- Make logo, CSS, report dynamic
- Added demonstration content showing static (ggplot) and HTML (plotly) plots using shinyngs functions. This R package provides quite a few of the necessary plotting packages, so will be handy even making new plots not defined there.

~~Just waiting on https://github.com/bioconda/bioconda-recipes/pull/38154,~~ but this establishes the basic functionality and will act as a basis for fleshing out the report going forward.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by pinin4fjords — APPROVED** [review]

**Comment by WackerO** [comment]
Thanks a lot @pinin4fjords!

**Comment by Shaun-Regenbaum** [comment]
Was documentation ever added for this. It seems an .rmd template is required now, but there is no documentation about what is acceptable as a template?

**Comment by pinin4fjords** [comment]
@Shaun-Regenbaum [this template](https://github.com/nf-core/differentialabundance/blob/master/assets/differentialabundance_report.Rmd) is used by default. But you could also supply your own by adapting that one. I'll add a line to document that in a future release.

**Comment by Shaun-Regenbaum** [comment]
Much appreciated.

**Pull request merged**
