### PR TITLE
Update test full profile

### PR DESCRIPTION
**Pull request by nschcolnicov**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nschcolnicov** [comment]
test full profile is now working:
image

**Comment by nschcolnicov** [comment]
@pinin4fjords @WackerO PR number in CHANGELOG.md is wrong, but Ill update it when I add the reviewers

**Comment by pinin4fjords** [comment]
Ahh, is this fallout from https://github.com/nf-core/differentialabundance/pull/304?

**Comment by nschcolnicov** [comment]
> Ahh, is this fallout from #304?

Exactly

**Review by pinin4fjords — APPROVED** [review]

**Comment by WackerO** [comment]
Oh good catch, thanks a lot!

**Pull request merged**
