### PR TITLE
Posible fix for issue #127

### PR DESCRIPTION
**Pull request by ctuni**
#127 This is a possible fix for the aforementioned issue. I tested both with `-profile test,docker` and with my data and infrastructure and the process that was failing on my case (`VALIDATOR`) is no longer failing. The `test` profile was not failing but it's working correctly with the fix also.

The change is made in the creation of `ch_input` channel, just adding `file()` around `params.input`. Apparently, this way the input matrix can be read as a file and it does not throw the error.

This change is made in line 17 of  `differentialabundance.nf` file.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

### CODE REVIEW

**Review by pinin4fjords — APPROVED** [review]
Looks sensible- thanks for the fix!

I’d normally object to lots of random spacing changes unrelated to the fix (presumably from your IDE), but it mostly seems to be rogue spaces being removed (@WackerO will be happy), and it’s come up before, so we’ll allow it ;-).

**Comment by pinin4fjords** [comment]
Ahh, wait, @ctuni - could you add the file existence check before you merge?

**Review by pinin4fjords — CHANGES_REQUESTED** [review]
Just need a file existence check

**Comment by ctuni** [comment]
HI! I'm sorry for the IDE and whitespaces thing, I did not realized it happened when pulling. I can try and re-do the PR with it but thanks for allowing it!

I added the file existence check also :)

**Comment by pinin4fjords** [comment]
> HI! I'm sorry for the IDE and whitespaces thing, I did not realized it happened when pulling. I can try and re-do the PR with it but thanks for allowing it!
> 
> I added the file existence check also :)

No, don’t worry, @WackerO had the same issue before, and the changes are harmless. Thanks for the fix.

**Review by pinin4fjords — APPROVED** [review]
LGTM now

**Comment by WackerO** [comment]
Well this is brilliant :D I was asking Cris to remove the whitespaces because I sensed a disturbance in the force and predicted your objection, @pinin4fjords! But yes, I am happy ^^

**Pull request merged**
