### PR TITLE
Fix low replication

### PR DESCRIPTION
**Pull request by pinin4fjords**
In this PR:

- Bump shinyngs modules for fixes feature name column for app building, and for skipping outlier plots with low replication. 
- Remove module hack necessary before the above
- Update markdown file to leverage the upstream fix

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Comment by pinin4fjords** [comment]
Thanks @nvnieuwk !

**Comment by pinin4fjords** [comment]
Sorry @nvnieuwk - forgot to add you as the reviewer in the changelog, will do it at the next PR.

**Comment by nvnieuwk** [comment]
No worries, it was a very small review 😆

**Pull request merged**
