### PR TITLE
Trivial change, not even a typo: Update README.md - Inserted missing blank.

### PR DESCRIPTION
**Pull request by smoe**
I only now found this workflow by chance, had manually performed the analysis of a nextflow-interpreted RNA-seq data.

### CODE REVIEW

**Review by WackerO — APPROVED** [review]
Thanks! Don't think we need to run the checks for a whitespace insertion in text :)

**Comment by WackerO** [comment]
Reminder to self: check this again after the template update

**Comment by pinin4fjords** [comment]
@nf-core-bot fix linting

**Comment by WackerO** [comment]
@smoe Hey Steffen, sorry, I completely forgot this. Could you please rerun the checks? Let's hope they finish now

**Comment by smoe** [comment]
@WackerO - here we go :)

**Comment by WackerO** [comment]
Thanks!

**Pull request merged**
